@extends('layout.main')


@section('content')

<div class="container">
    <h1>
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, hic cumque architecto nostrum molestiae maxime perferendis ipsa quae eveniet itaque quo nobis nihil totam nesciunt esse temporibus magni, tenetur numquam commodi corporis cum laborum ullam labore omnis. Ipsa eum veniam impedit ab, perspiciatis quisquam sed aspernatur similique et! Pariatur quaerat quo accusantium officiis eaque corrupti unde repudiandae ullam. Odio quasi nemo perferendis! Omnis numquam, necessitatibus earum dicta adipisci dolorem ducimus ea. Iure nesciunt alias saepe dignissimos animi, dolorem cumque est quae recusandae veniam, voluptatibus, molestiae minus quos reprehenderit qui earum in autem amet ipsum sint nam odio soluta? Consequatur veritatis error perferendis, iusto cum minus rerum perspiciatis reiciendis. Similique, doloremque sapiente impedit deserunt omnis sunt pariatur. Quod ut ullam modi dolorem quia ipsam sed et excepturi maxime suscipit, amet itaque dignissimos consectetur dolore, odio veritatis consequuntur voluptates officia laboriosam fuga ad hic aut at dolorum! Quos, nulla est? Magni labore veritatis suscipit, consectetur porro rerum. Itaque beatae officiis suscipit possimus vel aperiam unde nulla nostrum exercitationem illum animi tenetur modi alias quod, rem ea odio excepturi? Vitae, illum dolores recusandae culpa laborum, dolore cupiditate, repellat qui illo modi asperiores. Atque voluptates ab minus molestiae veniam optio totam libero reprehenderit. Quia, reprehenderit facilis. Praesentium fugit repudiandae nobis quia labore. Labore esse facilis officia debitis quibusdam enim iusto, culpa nulla possimus aspernatur voluptas reprehenderit totam est eveniet? Est deleniti illo nemo dolores velit accusamus reprehenderit, quasi esse maxime, hic officiis perferendis cum. Inventore, aut? Provident error accusamus dolorem esse rerum! Ipsam hic magnam rem doloribus veritatis nesciunt. Asperiores ullam eveniet accusamus et tenetur atque, commodi dolore deleniti illo id? Similique modi natus, laudantium distinctio asperiores officia inventore aperiam animi quas doloribus nostrum beatae facilis, labore ratione saepe tenetur nisi? Quis, hic quae amet recusandae ad, similique laudantium nesciunt placeat, repellat nostrum vel?
    </h1>
</div>
@endsection
